url: https://docs.textpattern.com
timezone: Europe/London
permalink: /:categories/:title
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
author: The Textpattern Development Team and contributors
exclude:
  - Gemfile
  - LICENSE.txt
  - README.md
kramdown:
  toc_levels: 2..4
highlighter: none
