url: https://docs.textpattern.com
timezone: Europe/London
permalink: /:categories/:title
plugins:
  - jekyll-feed
  - jekyll-pwa-plugin
  - jekyll-seo-tag
  - jekyll-sitemap
author: The Textpattern Development Team and contributors
exclude:
  - Gemfile
  - Gruntfile.js
  - LICENSE.txt
  - package.json
  - package-lock.json
  - README.md
  - src
kramdown:
  toc_levels: 2..4
highlighter: none
keep_files: [
  'expect-ct-report'
]
pwa: # See https://github.com/lavas-project/jekyll-pwa
  enabled: false # Optional
  sw_src_filepath: service-worker.js # Optional
  sw_dest_filename: service-worker.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html
  precache_glob_ignores: # Optional
    - sw-register.js
    - "fonts/**/*"
