url: https://docs.textpattern.com
timezone: Europe/London
permalink: /:categories/:title
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
author: The Textpattern Development Team and contributors
exclude:
  - Gemfile
  - Gruntfile.js
  - LICENSE.txt
  - package.json
  - README.md
  - src
kramdown:
  toc_levels: 2..4
highlighter: none
keep_files: [
  'expect-ct-report'
]
